# -*- coding: utf-8 -*-
"""WebScraping_SoccerStats_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wr_TW73rarIQXhB1R8s0xMamnFATwb7o

WebScraping do SoccerStats

Link: https://www.soccerstats.com/
"""

# Importando as Bibliotecas
import pandas as pd
import requests

from google.colab import data_table
data_table.enable_dataframe_formatter()

# Simulando navegador
header = {
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36",
  "X-Requested-With": "XMLHttpRequest"
}

# Url para acesso
url_link1 = "https://www.soccerstats.com/matches.asp?matchday=1&listing=1"
url_link2 = "https://www.soccerstats.com/matches.asp?matchday=1&listing=2"

#  requests
r1 = requests.get(url_link1, headers=header)
r2 = requests.get(url_link2, headers=header)

# E finalmente usamos a função read_html do pandas
df1 = pd.read_html(r1.text)
df2 = pd.read_html(r2.text)

# Comprimento da df1
len(df1)

# Comprimento da df2
len(df2)

# Acessando a df1
df1[6]

# Acessando a df2
df2[6]