# -*- coding: utf-8 -*-
"""Python para FUTEBOL_04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TZN2xOZMQpax4Q9C3PVVMW5B7jvEVbyc
"""

import pandas as pd

"""Laço que permite selecionar o Banco de Dados a ser consultado"""

liga = input("Digite a liga desejada: ")

if liga == "Inglaterra 1":
  # Inglaterra 1
  df1 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/E0.csv") 
  df2 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/E0.csv")  
elif liga == "Inglaterra 2":
  # Inglaterra 2
  df1 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/E1.csv") 
  df2 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/E1.csv")
elif liga == "Alemanha 1":
  # Alemanha 1
  df1 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/D1.csv") 
  df2 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/D1.csv")
elif liga == "Alemanha 2":
  # Alemanha 2
  df1 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/D2.csv") 
  df2 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/D2.csv")
elif liga == "Itália 1":
  # Itália 1
  df1 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/I1.csv") 
  df2 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/I1.csv")
elif liga == "Itália 2":
  # Itália 2
  df1 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/I2.csv") 
  df2 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/I2.csv")
elif liga == "Espanha 1":
  # Espanha 1
  df1 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/SP1.csv") 
  df2 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/SP1.csv")
elif liga == "Espanha 2":
  # Espanha 2
  df1 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/SP2.csv") 
  df2 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/SP2.csv")
elif liga == "França 1":
  # França 1
  df1 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/F1.csv") 
  df2 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/F1.csv")
elif liga == "França 2":
  # França 2
  df19 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/F2.csv") 
  df20 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/F2.csv")
else:
  print("Você digitou uma liga de maneira errada!")

df = [df1, df2]
df = pd.concat(df)
df

df = df [["Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR", "B365H", "B365D", "B365A"]]
df.columns = ["Data", "Mandante", "Visitante", "Gols do Mandante", "Gols do Visitante", "Resultado", "Odds Mandante", "Odds Empate", "Odds Visitante"]
df

df.to_excel(liga + ".xlsx")

"""# Nova seção"""