# -*- coding: utf-8 -*-
"""Python para FUTEBOL_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zuq9O3M2rMnnYRzEp8KbYlUj4B0eFTIi
"""

import pandas as pd

"""Aumentando o números de banco de dados consultados"""

df1 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/E0.csv")
df2 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/E0.csv")
df3 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/E0.csv")

"""Concatenando os BD's consultados"""

df = [df1, df2, df3]
df = pd.concat(df)
df

df = df [["Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR", "B365H", "B365D", "B365A"]]
df

"""Renomeando as colunas selecionadas"""

df.columns = ["Data", "Mandante", "Visitante", "Gols do Mandante", "Gols do Visitante", "Resultado", "Odds Mandante", "Odds Empate", "Odds Visitante"]
df

df.to_excel("PremierLeague.xlsx")