# -*- coding: utf-8 -*-
"""Python para FUTEBOL_05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TlQzFSEBPMc5724zy65dcFE7GJN2Qz9d
"""

import pandas as pd

df1 = pd.read_csv("https://www.football-data.co.uk/new/BRA.csv")
df2 = pd.read_csv("https://www.football-data.co.uk/new/JPN.csv")
df3 = pd.read_csv("https://www.football-data.co.uk/new/CHN.csv")

df = [df1, df2, df3]
df = pd.concat(df)
df

df = df [["Country", "Date", "Home", "Away", "HG", "AG", "Res", "PH", "PD", "PA"]]
df.columns = ["Liga", "Data", "Mandante", "Visitante", "Gols do Mandante", "Gols do Visitante", "Resultado", "Odds Mandante", "Odds Empate", "Odds Visitante"]
df

df.to_excel("Ligas_Secundárias.xlsx")

"""# Nova seção"""