# -*- coding: utf-8 -*-
"""Python para FUTEBOL_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w_e2NLdv2jGafhkPTH5h-kaJkifglRDo
"""

import pandas as pd

"""Expandindo os Banco de Dados possíveis para consulta

Primeiras e Segundas divisões de cinco países Europeus
"""

# Inglaterra 1
df1 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/E0.csv") 
df2 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/E0.csv")  
# Inglaterra 2
df3 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/E1.csv") 
df4 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/E1.csv")
# Alemanha 1
df5 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/D1.csv") 
df6 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/D1.csv")
# Alemanha 2
df7 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/D2.csv") 
df8 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/D2.csv")
# Itália 1
df9 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/I1.csv") 
df10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/I1.csv")
# Itália 2
df11 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/I2.csv") 
df12 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/I2.csv")
# Espanha 1
df13 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/SP1.csv") 
df14 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/SP1.csv")
# Espanha 2
df15 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/SP2.csv") 
df16 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/SP2.csv")
# França 1
df17 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/F1.csv") 
df18 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/F1.csv")
# França 2
df19 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/F2.csv") 
df20 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/F2.csv")

df = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16, df17, df18, df19, df20]
df = pd.concat(df)
df

df = df [["Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR", "B365H", "B365D", "B365A"]]
df.columns = ["Data", "Mandante", "Visitante", "Gols do Mandante", "Gols do Visitante", "Resultado", "Odds Mandante", "Odds Empate", "Odds Visitante"]
df

df.to_excel("db_europa.xlsx")